# Generated by Django 4.1.5 on 2023-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_myuser_is_admin_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
