# Generated by Django 4.1.5 on 2023-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_options_remove_myuser_birthday_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
